app/home/__init__.py
from flask import Blueprint


home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import (abort, current_app as app, flash, render_template,
                   redirect, request, send_from_directory, url_for)
from flask_login import current_user, login_required

from . import home
from ..models import Document, Meeting, User

import datetime
import os


@home.route('/')
def homepage():
    return render_template('home/index.html', title='Start')


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html', title="Pulpit")


@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/index.html', title='Pulpit')


@home.route('/documents/', defaults={'page': 1})
@home.route('/documents/<int:page>')
@login_required
def list_documents(page):
    user = User.query.get_or_404(current_user.get_id())
    documents = user.documents.paginate(page,
                                        app.config['ITEMS_PER_PAGE'])
    if documents.total == 0:
        flash('Brak dokumentów widocznych dla użytkownika %s.' %
              user.username, 'info')
    return render_template('home/list_documents.html',
                           documents=documents,
                           title='Lista dokumentów')


@home.route('/votes', defaults={'page': 1})
@home.route('/votes/<int:page>')
def list_votes(page):
    user = User.query.get_or_404(current_user.get_id())
    meetings = user.meetings.all()
    votes = {
        signature: documents
        for signature, documents
        in {
            meeting.signature: meeting.documents.filter_by(type_id=3).all()
            for meeting in meetings
        }.items() if documents
    }
    if not votes:
        flash('Brak uchwał widocznych dla użytkownika %s.' %
              user.username, 'info')
    return render_template('home/list_votes.html',
                           documents=votes)


@home.route('/documents/download/<int:document_id>')
@login_required
def download_document(document_id):  # todo: check user id before serving
    document = Document.query.get_or_404(document_id)
    if os.path.isfile(os.path.join(app.config['MEDIA_DIR'],
                      document.filename)):
        return send_from_directory(app.config['MEDIA_DIR'], document.filename,
                                   as_attachment=True)
    else:
        flash('Nie można pobrać dokumentu %s.' % document.filename, 'danger')
        return redirect(url_for('home.dashboard'))


@home.route('/meetings', defaults={'page': 1})
@home.route('/meetings/<int:page>')
@login_required
def list_meetings(page):
    user = User.query.get_or_404(current_user.get_id())
    year = request.args.get('year', default=0, type=int)
    if year:
        end = datetime.date(year=year, month=12, day=31)
        start = datetime.date(year=year, month=1, day=1)
        meetings = user.meetings\
                       .filter(Meeting.date <= end)\
                       .filter(Meeting.date >= start)\
                       .paginate(page, app.config['ITEMS_PER_PAGE'])
    else:
        meetings = user.meetings.paginate(page,
                                          app.config['ITEMS_PER_PAGE'])
    years = list(set([
        meeting.date.year for meeting in user.meetings.all()
    ]))
    board = False
    management = False
    if meetings.total == 0:
        flash('Brak posiedzeń widocznych dla użytkownika %s.' %
              user.username, 'info')
    else:
        for meeting in meetings.items:
            meeting.count = meeting.documents.count()
        if user.id == app.config['BOARD_ID']:
            board = True
        if user.id == app.config['MANAGEMENT_ID']:
            management = True
    return render_template('home/list_meetings.html',
                           board=board,
                           filters={'year': year, },
                           management=management,
                           meetings=meetings,
                           title='Lista posiedzeń',
                           years=years)


@home.route('/meetings/details/<int:meeting_id>')
@login_required
def meeting_details(meeting_id):
    meeting = Meeting.query.get_or_404(meeting_id)
    documents = meeting.documents.all()
    board = False
    management = False
    if current_user.id == app.config['BOARD_ID']:
        board = True
    if current_user.id == app.config['MANAGEMENT_ID']:
        management = True
    return render_template('home/meeting_details.html',
                           board=board,
                           documents=documents,
                           management=management,
                           meeting=meeting,
                           title='Szczegóły posiedzenia')

app/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<main>
    <h1 class="mb-5 text-center">Pulpit administratora</h1>
    <div class="row justify-content-center">
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('admin.upload_documents') }}">
            <i aria-hidden="true" class="d-block fa fa-upload fa-5x mb-3"></i>
            Załaduj<br>dokumenty
        </a>
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('admin.manage_documents') }}">
            <i aria-hidden="true" class="d-block fa fa-pencil-square-o fa-5x mb-3"></i>
            Zarządzaj<br>dokumentami
        </a>
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('admin.create_meeting') }}">
            <i aria-hidden="true" class="d-block fa fa-calendar-plus-o fa-5x mb-3"></i>
            Utwórz<br>posiedzenie
        </a>
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('admin.manage_meetings') }}">
            <i aria-hidden="true" class="d-block fa fa-calendar fa-5x mb-3"></i>
            Zarządzaj<br>posiedzeniami
        </a>
    </div>
</main>
{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<main>
    <h1 class="mb-5 text-center">Pulpit użytkownika</h1>
    <div class="row justify-content-center">
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('home.list_documents') }}">
            <i aria-hidden="true" class="d-block fa fa-file-text-o fa-5x mb-3"></i>
            Przeglądaj<br>dokumenty
        </a>
        <a class="btn btn-light col-5 col-sm-5 col-md-3 col-lg-2 mb-1 mx-1 text-center" href="{{ url_for('home.list_meetings') }}">
            <i aria-hidden="true" class="d-block fa fa-calendar fa-5x mb-3"></i>
            Przeglądaj<br>wydarzenia
        </a>
    </div>
</main>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Start{% endblock %}
{% block body %}
<main>
    <img alt="logo DokWew" class="d-block mt-3 mx-auto" src="{{ url_for('static', filename='images/dokwew-logo.svg') }}">
</main>
{% endblock %}

app/templates/home/list_documents.html
{% from "macros.html" import render_pagination %}
{% extends "base.html" %}
{% block title %}Przeglądaj dokumenty{% endblock %}
{% block body %}
<main>
    {% if documents.items|length > 0 %}
    <h3 class="mb-5 text-center">Lista dokumentów</h3>
    <ol>
        {% for document in documents.items %}
        <li">
                <span class="d-inline-block mb-1">{{ document.description }}</span><br />
                <a class="link-unstyled" href="{{ url_for('home.download_document', document_id=document.id) }}" title="Pobierz {{ document.filename }}">
                    <i class="fa fa-download mr-1" aria-hidden="true"></i>
                    <span class="small">{{ document.filename|substr }}</span>
                </a>
        </li>
        {% endfor %}
    </ol>
        {{ render_pagination(documents, 'home.list_documents') }}
    {% endif %}
</main>
{% endblock %}
{% block scripts %}
{% endblock %}

app/templates/home/list_meetings.html
{% from "macros.html" import render_pagination %}
{% extends "base.html" %}
{% block title %}Przeglądaj wydarzenia{% endblock %}
{% block body %}
<main>
    {% if meetings.items|length > 0 %}
    <h3 class="mb-5 text-center">Lista posiedzeń</h3>
    <div class="row">
        <ul class="list-inline">
            <li class="list-inline-item">
                <i aria-hidden="true" class="fa fa-calendar"></i>
                Pokaż tylko rok:
            </li>
        {% for year in years %}
            <li class="list-inline-item">
                <a href="{{ url_for('home.list_meetings', year=year) }}">{{ year }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
        {% for meeting in meetings.items %}
    <div class="my-3 row">
        <div class="col-8 mr-auto px-0">
            <a class="link-unstyled" href="{{ url_for('home.meeting_details', meeting_id=meeting.id) }}">
            {{ meeting.signature }} Posiedzenie
            {% if board %}Rady {% endif %}
            {% if management %}Zarządu {% endif %}
            Izby
            </a>
        </div>
        <div class="col-auto">
            <a class="link-unstyled" href="{{ url_for('home.meeting_details', meeting_id=meeting.id) }}">
            {{ meeting.date|dateformat }}
            </a>
        </div>
    </div>
        {% endfor %}
        {{ render_pagination(meetings, 'home.list_meetings', filters) }}
    {% endif %}
</main>
{% endblock %}
{% block scripts %}
{% endblock %}

app/templates/home/list_votes.html
{% extends "base.html" %}
{% block title %}Przeglądaj dokumenty{% endblock %}
{% block body %}
<main>
    {% if documents|length > 0 %}
    <h3 class="mb-5 text-center">Lista uchwał</h3>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Numer posiedzenia</th>
                <th scope="col">Numer uchwały</th>
                <th scope="col">Treść uchwały</th>
                <th scope="col">Pobierz</th>
            </tr>
        </thead>
        <tbody>
        {% for meeting_signature, votes in documents.items() %}
            {% set outer_loop = loop %}
            {% for vote in votes %}
            <tr>
                {% if not loop.index0 %}
                <td rowspan="{{ votes|length }}">
                    {{ meeting_signature }}
                </td>
                {% endif %}
                <td class="text-center">
                {{ vote.signature }}
                </td>
                <td>
                {{ vote.description }}
                </td>
                <td class="text-center">
                    <a href="{{ url_for('home.download_document', document_id=vote.id) }}" title="Pobierz {{ vote.filename }}"><i class="fa fa-download" aria-hidden="true"></i></a>
                </td>
            </tr>
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
</main>
{% endblock %}
{% block scripts %}
{% endblock %}

app/templates/home/meeting_details.html
{% extends "base.html" %}
{% block title %}Szczegóły wydarzenia{% endblock %}
{% block body %}
<main>
    <h3 class="mb-5 text-center">Szczegóły posiedzenia</h3>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-2"><strong class="text-dark">Nazwa:</strong></div>
        <div class="col">
        {{ meeting.signature }} Posiedzenie
        {% if meeting.board %}Rady {% endif %}
        {% if meeting.management %}Zarządu {% endif %}
        Izby z dnia {{ meeting.date|dateformat }}
        </div>
    </div>
    <div class="my-3 row">
        <div class="col-12 col-sm-12 col-md-2"><strong class="text-dark">Podsumowanie:</strong></div>
        <div class="col text-justify">
        {{ meeting.summary }}
        </div>
    </div>
    {% if documents|length > 0 %}
        {% for document in documents %}
    <div class="align-items-top my-3 row">
        <div class="col-12 col-lg-8 col-md-8 mb-3 mb-md-0 mr-md-auto">
            <div class="row">
                <div class="col-12">
                    <i aria-hidden="true" class="fa fa-2x fa-paperclip mr-1"></i><span title="{{ document.filename }}"> {{ document.filename|substr }}</span>
                    <a class="link-unstyled ml-3" href="{{ url_for('home.download_document', document_id=document.id) }}" title="Pobierz {{ document.filename }}">
                        <i class="fa fa-download mr-1" aria-hidden="true"></i>
                    </a>
                </div>
                {% if document.description %}
                <div class="col-12 mt-3 rounded small text-muted">
                    <span class="d-inline-block">
                        <strong>Opis: </strong>{{ document.description }}
                    </span>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="col-6 col-md-auto mr-auto mr-md-0">
            <span class="badge badge-pill badge-dark" title="Typ i oznaczenie dokumentu">
                {{ document.type.name }}
                {% if document.type.signature_required %}
                    nr {{ document.signature }}
                {% endif %}
            </span>
        </div>
    </div>
        {% endfor %}
    {% else %}
    <div class="alert alert-info">
        Do tego posiedzenia nie przypisano żadnych dokumentów.    
    </div>
    {% endif %}
</main>
{% endblock %}
{% block scripts %}
{% endblock %}